name: access-tests
on: [push]
jobs:
  run-code-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x', 'pypy-3.6', 'pypy-3.7']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python -m pip install --upgrade pip
      - run: python3 -m pip install --upgrade pip
      - run: python -m pip install babel>=2.10
      - run: pip install codecov
      - run: pip install coveralls
      - run: pip install nose-show-skipped
      - run: pip install mock
      - run: pip install setuptools
      - run: pip install --upgrade httpcore
      - run: python setup.py install
      - run: coverage run access-tests.py
      - run: codecov
      - run: coveralls
            
